# Generated by Django 2.2.3 on 2019-07-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=0, max_length=100, verbose_name='الاسم الكامل'),
            preserve_default=False,
        ),
    ]
