# Generated by Django 2.2.3 on 2019-10-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_img_url',
            field=models.URLField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
