# Generated by Django 2.2.3 on 2019-11-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191109_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
