# Generated by Django 2.2.3 on 2019-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=50, unique=True)),
                ('board_image', models.ImageField(blank=True, default=True, upload_to='images')),
            ],
        ),
    ]
