# Generated by Django 2.2.3 on 2019-07-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190730_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide_Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slide_img', models.ImageField(blank=True, default=True, upload_to='images')),
            ],
        ),
    ]
