# Generated by Django 2.2.3 on 2019-07-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_slide_advertising_slide_img_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide_advertising',
            name='Slide_img',
        ),
    ]
