# Generated by Django 2.2.3 on 2019-08-01 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_main_advertising_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='board.Topic')),
            ],
        ),
    ]
