# Generated by Django 2.2.3 on 2019-08-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_desiner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desiner',
        ),
    ]
