# Generated by Django 2.2.3 on 2019-08-05 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_remove_profile_full_name'),
        ('board', '0011_delete_desiner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('AD_profile', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topic_Advertising', to='users.Profile')),
                ('name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topic_Advertising', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
