# Generated by Django 2.2.3 on 2019-08-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_topic_advertising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
