# Generated by Django 2.2.3 on 2019-08-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20190805_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
