# Generated by Django 2.2.3 on 2019-08-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_auto_20190805_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board_image',
        ),
        migrations.AlterField(
            model_name='board',
            name='active',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='active',
            field=models.BooleanField(blank=True),
        ),
    ]
