# Generated by Django 2.2.3 on 2019-09-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_auto_20190924_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_advertising',
            name='all_topics',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_topics', to='board.Topic'),
        ),
    ]
