# Generated by Django 2.2.3 on 2019-09-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_topic_advertising_all_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic_advertising',
            name='all_topics',
        ),
    ]
