# Generated by Django 2.2.3 on 2019-10-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_remove_topic_advertising_all_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_advertising',
            name='AD_topics',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_topics', to='board.Board'),
        ),
    ]
