# Generated by Django 2.2.3 on 2019-10-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_up_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main_Advertising',
        ),
    ]
