# Generated by Django 2.2.3 on 2019-10-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_delete_main_advertising'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic_advertising',
            name='AD_topics',
        ),
        migrations.AddField(
            model_name='topic_advertising',
            name='topic_cret',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topic_Advertising', to='board.Topic'),
        ),
    ]
