# Generated by Django 2.2.3 on 2019-10-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_auto_20191010_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic_advertising',
            name='topic_cret',
        ),
        migrations.AddField(
            model_name='topic_advertising',
            name='url_adv',
            field=models.URLField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
