# Generated by Django 2.2.3 on 2019-10-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_auto_20191011_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
