# Generated by Django 2.2.3 on 2019-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_auto_20191020_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='update_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
