# Generated by Django 2.2.3 on 2019-11-13 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_auto_20191113_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='update_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
