# Generated by Django 2.2.3 on 2019-11-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0030_remove_topic_update_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
